### ISSUE TITLE
How to fix this error?

### ISSUE THREAD

**Issue by JeoriTr** [FBFunnyBunnyFB/telebunny#1]
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: 🐰 [TeleBunny] ~ 429 Too Many Requests: retry after 6
    at new TeleBunnyError (.....bot/node_modules/telebunny/lib/telebunny.js:17:16)
    at TeleBunny.<anonymous> ...../bot/node_modules/telebunny/lib/telebunny.js:148:23)
    at Generator.next (<anonymous>)
    at fulfilled (...../bot/node_modules/telebunny/lib/telebunny.js:4:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: 🐰 [TeleBunny] ~ 429 Too Many Requests: retry after 6
    at new TeleBunnyError (...../bot/node_modules/telebunny/lib/telebunny.js:17:16)
    at TeleBunny.<anonymous> (...../bot/node_modules/telebunny/lib/telebunny.js:148:23)
    at Generator.next (<anonymous>)
    at fulfilled (...../bot/node_modules/telebunny/lib/telebunny.js:4:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by FBFunnyBunnyFB** [comment]
Thank you for your feedback

[Telegram Bot API](https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this) limits you sending a lot of requests in a short period of time. If your app makes too many requests you'll get this error. Try to use methods with some interval or make requests one after another using [.then()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then) or [await](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await).

Happy coding :man_technologist:

**Comment by JeoriTr** [comment]
when i update telebunny to version 0.8.0 i get error like below:
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: 🐰 [TeleBunny] ~ read ECONNRESET
    at new TeleBunnyError (......./bot/node_modules/telebunny/lib/telebunny.js:17:16)
    at TeleBunny.<anonymous> (......./bot/node_modules/telebunny/lib/telebunny.js:278:27)
    at Generator.throw (<anonymous>)
    at rejected ......./bot/node_modules/telebunny/lib/telebunny.js:5:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by FBFunnyBunnyFB** [comment]
Seems like there is a problem with connection. Can you provide more details? When and how error occurs?
